### ISSUE TITLE
Commands different

### ISSUE THREAD

**Issue by Dunk0w0** [Darkhax-Minecraft/Runelic#11]
Something I've noticed is that the commands are different ingame than what it says they are on here and on curseforge. In game the command is /bookshelf and is formatted differently than how on the page it says it's /runelic. Not a huge deal but it is a little strange. I am using quilt so that might be why but I'm not sure.

**Comment by Darkhax** [comment]
Hello, you're correct. I maintain a few mods that add new font packs to the game and they each had their own commands which were virtually identical. I made a new version of the command in my library mod Bookshelf which is similar but works for any font registered on the client rather than just one specific font. I felt this would be more useful to players and it will hopefully make it easier for me to add new features over time. This change happened somewhere between 1.18.2 and 1.19.2 and the information pages have not been updated to reflect that.

**Comment by Dunk0w0** [comment]
Alright no worries! The new way of doing it works just fine, the only thing it's missing is the ability to change the language of written books. But otherwise it's fine the way it is!

**Comment by Darkhax** [comment]
You should be able to use `/bookshelf font book <fontid>` to change written books.
