### ISSUE TITLE
[BUG] Missing banner patterns

### ISSUE THREAD

**Issue by Endy229** [Darkhax-Minecraft/Runelic#17]
### Minecraft Version

1.20.1

### Mod Version

18.0.2

### Mod Loader

Fabric

### What environment are you running the mod in?

Client

### Issue Description

Apparently some banner patterns are missing. When I try to apply some of them on the banners, they don't display 
![изображение_2024-02-23_111627200](https://github.com/Darkhax-Minecraft/Runelic/assets/122396550/a6f016e6-3821-4932-bc29-250925d167ae)
![изображение_2024-02-23_111645271](https://github.com/Darkhax-Minecraft/Runelic/assets/122396550/081f72c2-5b31-4f0b-a731-bc453353a361)

**Comment by Darkhax** [comment]
Hello, unfortunately this is a bug introduced by another mod. There are a few different causes, but it's usually caused by mods building the texture atlas too early or messing with the game data. I would recommend going through and removing mods related to textures/rendering/shaders/performance until you can find out which one and then report it to them. 

I've also created a profile with the versions you listed and can verify that the Rune 1 pattern is definitely not missing.  
![image](https://github.com/Darkhax-Minecraft/Runelic/assets/2250798/b504f4e4-c254-4ed4-af42-7e6c4ae8e83f)
